### ISSUE TITLE
Upgrade it's Readme.md file

### ISSUE THREAD

**Issue by jagroop-dev-11** [Jagroop2001/validify-string#1]
**Rewrite the readme.md file for validify-string  project:**

- Add project details.
- Include a demo (screenshot, video, or gif) 
- Include contribution guidelines.
- Include other relevant items, but please indicate them in the comments.

**Comment by Anushkabh** [comment]
Hey @Jagroop2001 ,
I would like to work on this issue.
Would really appreciate if you assign me this issue

**Comment by jagroop-dev-11** [comment]
Go ahead @Anushkabh  !!

**Comment by Anushkabh** [comment]
@Jagroop2001 i am facing difficulties in running the project in my local setup. i have done other things . kindly help

**Comment by jagroop-dev-11** [comment]
Hi @Anushkabh , please change your node version

**Comment by jagroop-dev-11** [comment]
use 14.19.0, also for updati ng readme.md , you don't even require to run code.

**Comment by rakesh-paulraj** [comment]
i would like to work on this project under jwoc

**Comment by Anushkabh** [comment]
Okay @Jagroop2001 I will update the readme

**Comment by rakesh-paulraj** [comment]
I would like to work on this under JWOC

**Comment by rakesh-paulraj** [comment]
as Its been a week can i take this issue under JWOC

**Comment by Anushkabh** [comment]
@Jagroop2001  i have competed .. kindly merge if satisfied #20
