### ISSUE TITLE
Add Validation of isAscii

### ISSUE THREAD

**Issue by jagroop-dev-11** [Jagroop2001/validify-string#14]

**Comment by vishal2005025** [comment]
I would like to work on this issue .
please assign it to me under JWOC'2024

**Comment by JavidSumra** [comment]
Hey @Jagroop2001 Shall I need to Check for Single Character and I would Like to Work on This Issue under JWOC 2024.

**Comment by Jagroop2001** [comment]
@vishal2005025 , go for it.

**Comment by Jagroop2001** [comment]
@JavidSumra , please create a new issue and suggest a different utility function.

**Comment by jagroop-dev-11** [comment]
@JavidSumra , go for it.

**Comment by JavidSumra** [comment]
Hey @Jagroop2001 can you please explain something about this function?

**Comment by vishal2005025** [comment]
Sir, I can solve this issue.
Please assign it to me under JWOC'2024.

**Comment by jagroop-dev-11** [comment]
@JavidSumra , take this as reference  : https://stackoverflow.com/questions/14313183/javascript-regex-how-do-i-check-if-the-string-is-ascii-only

**Comment by JavidSumra** [comment]
Hey @Jagroop2001 Sir Please Checkout My PR.
