### ISSUE TITLE
Add below mentioned validators : 1

### ISSUE THREAD

**Issue by jagroop-dev-11** [Jagroop2001/validify-string#15]
Create a new ts file were you have below validators : 
- isBase32
- isBase64
- isEthereumAddress

**Comment by vishal2005025** [comment]
I would like to work on this issue .
please assign it to me under JWOC'2024

**Comment by jagroop-dev-11** [comment]
@vishal2005025 , go for it.

**Comment by vishal2005025** [comment]
Sir, I have to make seperate file for these validations or write in utilityfunctions.ts file .
What should I do?

**Comment by jagroop-dev-11** [comment]
You can create a separate file @vishal2005025

**Comment by JavidSumra** [comment]
Hey @Jagroop2001 Sir is There any one Working on it or I Can Work on it Under JWOC 2024

**Comment by vishal2005025** [comment]
I am Working on this Issue and create pr by today.
