### ISSUE TITLE
Add below mentione validators : 2

### ISSUE THREAD

**Issue by jagroop-dev-11** [Jagroop2001/validify-string#16]
Create a new ts file where one should cover : 
- isHexColor
- isJSON
- isJWT

**Comment by rakesh-paulraj** [comment]
i would like to work on this under jwoc

**Comment by jagroop-dev-11** [comment]
@rakesh-paulraj , go for it

**Comment by rakesh-paulraj** [comment]
can i  get some references

**Comment by jagroop-dev-11** [comment]
Here it is  : https://github.com/validatorjs/validator.js

**Comment by rakesh-paulraj** [comment]
SORRY TO SAY THIS PLEASE DE ASSIGN IT TO SOMEONE ELSE

**Comment by rakesh-paulraj** [comment]
please assign it to someone else

**Comment by professor1412** [comment]
please assign it to me

**Comment by jagroop-dev-11** [comment]
@professor1412 ,go for it.
