### ISSUE TITLE
Add below mentioned validator's : 3

### ISSUE THREAD

**Issue by jagroop-dev-11** [Jagroop2001/validify-string#17]
Create a new ts file where one should cover below validator's : 
- isHash
- isHexadecimal
- isAlphanumeric

**Comment by debuuuu007** [comment]
Can you just explain a little more of what does this project do, so that i can contribute in it. Also whats about this issue.

**Comment by debuuuu007** [comment]
I would like to contribute in it, I understood what the project is of. Just i have to make functions for the respective issues in typescript. 

You can assign me under JWOC24.
