### ISSUE TITLE
Change color on hover to light green

### ISSUE THREAD

**Issue by jagroop-dev-11** [Jagroop2001/validify-string#19]
![Screenshot from 2024-01-22 21-11-02](https://github.com/Jagroop2001/validify-string/assets/99062463/40190f1f-1c6f-4157-b166-fd53cef05923)
On hover change color to light green.

**Comment by vishal2005025** [comment]
I would like to work on this issue .
please assign it to me under JWOC'2024.

**Comment by Jenis07** [comment]
Can you please assign me this issue under JWOC?
