### ISSUE TITLE
Add Eslineter to this project

### ISSUE THREAD

**Issue by jagroop-dev-11** [Jagroop2001/validify-string#2]
Add Eslinter to this typescript project

**Comment by rakesh-paulraj** [comment]
You mean eslint right if it is i would like to work on the project under jwoc

**Comment by jagroop-dev-11** [comment]
Hi @rakesh-paulraj  !!
Go ahead

**Comment by jagroop-dev-11** [comment]
https://github.com/Jagroop2001/validify-string/pull/7
