### ISSUE TITLE
Adding of String Comparison

### ISSUE THREAD

**Issue by jagroop-dev-11** [Jagroop2001/validify-string#24]
Add below mentioned features : 
 
- check if the string A contains the string B
- check if the string A matches the string B.

**Comment by Prithwi32** [comment]
@Jagroop2001 I would like to work on this issue under JWOC

**Comment by vishal2005025** [comment]
sir , I would like to work on this issue , I have solution of this Issue and created pr till Tomorrow ..
Please assign it to me under JWOC'2024.

**Comment by jagroop-dev-11** [comment]
@Prithwi32 , go for it.

**Comment by jagroop-dev-11** [comment]
@vishal2005025 , please either choose unassigned issues or suggest a new one.

**Comment by Prithwi32** [comment]
> @Prithwi32 , go for it.

@Jagroop2001  Sure, I would like to know where should I include this feature? ..I mean in which folder,,,should I create saperate StringCompare.ts file?

**Comment by jagroop-dev-11** [comment]
You should create a new `.ts` file @Prithwi32
