### ISSUE TITLE
Sanitizers : Sanitize strings

### ISSUE THREAD

**Issue by jagroop-dev-11** [Jagroop2001/validify-string#25]
Please implement below methods : 

- trim characters from the left-side of the input.
- trim characters from the right-side of the input.
- trim characters from the both-side of the input.

**Comment by Anushkabh** [comment]
i would like to work under jwoc @Jagroop2001 kindly assign

**Comment by jagroop-dev-11** [comment]
@Anushkabh , go for it.

**Comment by vishal2005025** [comment]
Sir, I would like to work on this issue.
Please assign it to me under JWOC'2024

**Comment by Anushkabh** [comment]
@Jagroop2001 i have completed .. kindly merge if satisfied

**Comment by Parth4git** [comment]
@Jagroop2001 I want to work on this issue

**Comment by Anushkabh** [comment]
> @Anushkabh , go for it.

i have completed .. kindly merge the pr #28
