### ISSUE TITLE
Add more utlity functions for validating stings.

### ISSUE THREAD

**Issue by jagroop-dev-11** [Jagroop2001/validify-string#3]
Add more utlity functions for validating stings : 
I will change the tag accordingly depending upon the number of utility functions added to validate sting.

**Comment by singhcodes26** [comment]
You can assign me this issue under JWOC

**Comment by ayesha-2101** [comment]
@Jagroop2001 I am willing to do this under JWOC. Please assign this to me

**Comment by jagroop-dev-11** [comment]
You both @singhcodes26  and @ayesha-2101 , can work on this issue.
Create a separate issue with the explanation regarding which utility function you are going to add. If it's not existed I will assign that issue to you.

**Comment by vipul-dixit-2004** [comment]
we can add,
1.) Is valid phone number: (checks for valid mobile number entered, i.e. 10 numeric characters only)
2.)Date format Validator: (Verify if a string represents a valid date in a specific format.)
3.)Credit Card Number Validator(Using Luhn's algorithm)
I have these in mind for the time being but will add more later.
Really excited to work on this project. 
@Jagroop2001 kindly assign this to me.

**Comment by jagroop-dev-11** [comment]
@vipul-dixit-2004  !!
Please create a new Issue for this.

**Comment by vermaanurag1532** [comment]
please assign it to me i have worked on node js i can resolve it for you

**Comment by jagroop-dev-11** [comment]
@vermaanurag1532 , create a new issue with the utility functions name.
