### ISSUE TITLE
JWT Generator on the basis of object passed to function

### ISSUE THREAD

**Issue by jagroop-dev-11** [Jagroop2001/validify-string#36]

**Comment by Jenis07** [comment]
what this issue try to solve?

**Comment by jagroop-dev-11** [comment]
@Jenis07 , go  for it.

**Comment by Jenis07** [comment]
can you brief description about it?

**Comment by jagroop-dev-11** [comment]
Okay @Jenis07 , 
Object for example :
```
{
email : "abc@yopmail.com",
userId: "user_test",
date :  new Date()
}
```

is passed as input and JWT Generator function encode it and convert it into standard JWT.
You can use any other npm package here or do with with js only.

**Comment by yashasvini121** [comment]
Hi @Jagroop2001, because of inactivity, I would like to work on this issue under JWOC.
