### ISSUE TITLE
More Utility functions

### ISSUE THREAD

**Issue by singhcodes26** [Jagroop2001/validify-string#4]
I can add more utility functions under JWOC
1. validator.isUpperCase(str):
Check if the entire string is in uppercase.
2. validator.isLowerCase(str):
Check if the entire string is in lowercase.
3. validator.isDate(str):
Check if the string represents a valid date.
4. validator.isPalindrome(str):
Check if the string is a palindrome.

**Comment by jagroop-dev-11** [comment]
@singhcodes26  !!
Go for it !!

**Comment by amanswarnakar** [comment]
Hey @Jagroop2001, I would like to work on this issue under JWOC'24

**Comment by jagroop-dev-11** [comment]
@amanswarnakar , you can create a new issue with different utility functions

**Comment by jagroop-dev-11** [comment]
https://github.com/Jagroop2001/validify-string/pull/9
