### ISSUE TITLE
More Utility Functions 

### ISSUE THREAD

**Issue by vipul-dixit-2004** [Jagroop2001/validify-string#5]
We can add,
1.) Is valid phone number: (checks for valid mobile number entered, i.e. 10 numeric characters only)
2.)Date format Validator: (Verify if a string represents a valid date in a specific format.)
3.)Credit Card Number Validator(Using Luhn's algorithm)
I have these in mind for the time being but will add more later.
Kindly assign me this under JWoC 2024.
Thank You

**Comment by jagroop-dev-11** [comment]
@vipul-dixit-2004 , go for it !!

**Comment by jagroop-dev-11** [comment]
https://github.com/Jagroop2001/validify-string/pull/8
