### ISSUE TITLE
Adding more utility functions for validating strings 

### ISSUE THREAD

**Issue by ayesha-2101** [Jagroop2001/validify-string#6]
@Jagroop2001 I am thinking of adding these 
(i) Valid Email
(ii) Valid URL 
(iii) Valid Date Format 

I was asked to create a new issue for this. Please assign this to me @Jagroop2001  UNDER JWOC

**Comment by jagroop-dev-11** [comment]
Hi @ayesha-2101 ,
above mentioned  validators are already in project or someone has taken. you can suggest other's

**Comment by ayesha-2101** [comment]
@Jagroop2001 
Valid IP address

**Comment by jagroop-dev-11** [comment]
@ayesha-2101 , go for it.

**Comment by ayesha-2101** [comment]
done @Jagroop2001
